### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by AlexandreIorio** [heig-vd-dai-course/heig-vd-dai-course#104]
There is a link error in [practical work - IMAP official RFC link](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/09-define-an-application-protocol/COURSE_MATERIAL.md#better-understand-the-imap-protocol).

Here is the correct link :[https://datatracker.ietf.org/doc/rfc3501/](https://datatracker.ietf.org/doc/rfc3501/)

**Comment by ludelafo** [comment]
Thank you very much for the report, I will fix this as soon as possible!
