### ISSUE TITLE
Twitch UDP

### ISSUE THREAD

**Issue by AlexandrePhilibert** [heig-vd-dai-course/heig-vd-dai-course#170]
[This](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/17-java-udp-programming/COURSE_MATERIAL.md#reliability) paragraph of the documentation mentions that Twitch is using UDP to deliver livestreams. I am not able to get twitch to send me the video feed in UDP. I am only able to get HTTP/1.1 or HTTP/2 responses.

I also tried to look for UDP packets in wireshark but I can't find any.

Providing another example such as Teams / Google Meet could help, as these apps seem to be using WebRTC in UDP mode (but then again, WebRTC can also be implemented in TCP...).

**Comment by ludelafo** [comment]
Thank you for your comment!

You are right, Twitch mentions the [Real-Time Messaging Protocol (RTMP)](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol) in their [official](https://dev.twitch.tv/docs/video-broadcast/) documentation, which is based on TCP...

I will update the course material after the evaluation (to avoid any confusion) with the following content:

> For example, streaming can be a perfect use case for UDP. If a datagram is lost, it does not matter much: the receiver will receive the next datagram and the stream will continue. A good example would be the streaming of a live event on your television: 
>
> - If a few datagrams are lost, the receiver might notice it with a few glitches (video artifacts) but it will not affect the entire stream.
> - If too many datagrams are lost, the receiver will not be able to reassemble the payload and the stream will stop.
>
> Some video services such as [Jitsi](https://jitsi.org/) (an open source Zoom/Google Meet/Teams alternative) can make usage of the UDP protocol with the help of [WebRTC](https://webrtc.org/). However, even these applications might prefer to make usage of the TCP protocol to guarantee the reliability of their services.

What do you think?
